# Use an nginx image to serve static content
FROM nginx:alpine

# Copy the built frontend files to the appropriate directory in the container
COPY . /usr/share/nginx/html

# Expose port 80 for the nginx server
EXPOSE 80
